### ISSUE TITLE
加入会议失败

### ISSUE THREAD

**Issue by stuartZhang** [xylink-com/xylink-rtc-vue-demo#4]
大神，

我是【北京德惠众合信息技术有限公司】的前端开发。我们团队想在自己的产品里集成贵团队的优秀产品。特此，分别`git clone`与`npm start`运行了`master`与`v3.9.1`分支的代码。

# 问题现象

在这两个分支的演示代码上，我们团队都遇到了：“点击【加入会议】按钮之后，提示【获取用户信息失败】的错误”。
![image](https://github.com/xylink-com/xylink-rtc-vue-demo/assets/13935927/b67b1581-754b-4e2f-863c-41dba6a2a4bf)

# 运行环境

1. `Windows 11` 家庭中文版`22621.2506`
2. `npm@6.14.16`
3. `node@v12.22.12`

## 产品配置

* `wssServer`，`httpServer`，`logServer`，`extId`，`clientId`，和`clientSecret`是由您们团队客服提供的，所以不方便显露在这个公开位置。
* 第三方账号ID：13170912329
* 会议号：913170912329
* 显示名称：敏行测试

# 网络异常

![image](https://github.com/xylink-com/xylink-rtc-vue-demo/assets/13935927/e41bf560-92e4-40b2-adce-b2aa3113704f)

我本地`npm start`的网址是`https://localhost:8080/`。所以，这明显是跨问题。我猜测：是否是由于此`Restful API`请求失败造成的【获取用户信息失败】。

# 报障代码位置

`client.loginExternalAccount({ displayName: 'thirdName', extId, extUserId,})`接口返回了 {code: "XYSDK:950120", msg: "获取用户信息失败"}

![image](https://github.com/xylink-com/xylink-rtc-vue-demo/assets/13935927/c25703ea-1d22-433c-92d1-095cde539953)

大神们，有什么解决办法吗？

**Comment by luojinghui** [comment]
你好，根据提交的会议号信息呼叫测试，我们发现呼叫的会议号不是公有云的会议室号码，猜测可能是分区云交付项目，请联系对应的小鱼项目交付同学或者产品经理，以便通过技术途径沟通更好的解决问题。

上面的问题提供以下的一些排查思路：
1、本地开发调试可以使用`http://localhost`协议运行WebRTC，无需转换成https，部署上线需要ssl证书；
2、如果是分区云项目，没有办法使用最新的sdk3.9.1版本，需要降级到对应的版本；
3、如果是公有云项目，demo中提供了测试的clientId/clientSecret/extId信息，无需配置server地址；
4、确保呼叫的是正确的号码；
