### ISSUE TITLE
vue版本的demo缺少功能

### ISSUE THREAD

**Issue by chenchenwuai** [xylink-com/xylink-rtc-vue-demo#6]
hello，vue版本的demo与现在的小鱼官网和react版本demo相比，缺少了很多功能，请问这个有计划同步功能吗？

**Comment by luojinghui** [comment]
@chenchenwuai 
暂时没有计划同步功能，小鱼官网Web会议所有功能是基于WebSDK实现，开发者可以基于[集成文档](https://openapi.xylink.com/common/meeting/doc/description?platform=web)或者react demo参考实现
